---
repo-name: peripherals-dropbox
categories:
- Storage
display-name: Dropbox
manufacture: Dropbox Inc.
description: Dropbox is a home for all your work. You can store and share files, collaborate on projects, and bring your best ideas to life—whether you're working alone or with colleagues and clients. With Dropbox, all your files are backed up to the cloud and available online.
